version = 3

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
  template = '╭── {{.Icon}}'
  foreground = 'cyan'
  type = 'os'

  [[blocks.segments]]
  type = 'path'
  template = '  at 󰉋  {{.Path}}'
  foreground = 'cyan'

    [blocks.segments.properties]
    style = 'full'

    [[blocks.segments]]
    template = ' :: {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = '#F1502F'
    type = 'git'
    style = 'plain'

      [blocks.segments.properties]
          branch_icon = ''
          commit_icon = '@'
          fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    template = '{{ div .Ms 1000 }}s'

      [blocks.segments.properties]
        threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─── $ '
    foreground = 'lightGreen'
    type = 'status'
    style = 'powerline'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}lightGreen{{end}}",
    ]

    [blocks.segments.properties]
    always_enabled = true


[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '➜ '

[secondary_prompt]
  foreground = 'lightGreen'
  template = '─ '
