hl.on("hyprland.start", function()
	hl.exec_cmd("swaync")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("xrandr --output DP-2 --primary")
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaybg -i " .. require("edgar.vars").wallpaper)
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
end)
